POST http://localhost:3030/api/blogs HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluQGdtYWlsLmNvbSIsImlkIjo1LCJpYXQiOjE3NTI2NzIzNTZ9.BRzsswTpjkKuYqUwU9v4SRELPGl_3GCBoHWeRlXrRWE

{
    "author": "Admin",
    "url": "www.blogadmin.com/31",
		"title": "How to login",
		"likes": 1
}

###

PUT http://localhost:3030/api/blogs/2 HTTP/1.1
content-type: application/json

{
		"likes": 3
}

###

DELETE http://localhost:3030/api/blogs/3 HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IndpdGhtYWlscG9hcEBnbWFpbC5jb20iLCJpZCI6NCwiaWF0IjoxNzUyNjI0NjE5fQ.I9ctZqr9vO4oh9ZuNvEDPC1W4MnZvD4x467DEMRJ-CU

### bad POST request
POST http://localhost:3030/api/blogs HTTP/1.1
content-type: application/json

{
    "author": "Poap",
		"title": "A new blog example",
		"likes": 0
}

### PUT request
PUT http://localhost:3030/api/blogs/4 HTTP/1.1
content-type: application/json

{
		"likes": 2
}

###
GET http://localhost:3030/api/users HTTP/1.1
content-type: application/json

###
GET http://localhost:3030/api/blogs?search=blog HTTP/1.1
content-type: application/json

###
POST http://localhost:3030/api/users HTTP/1.1
content-type: application/json

{
    "name": "Admin",
		"username": "admin@gmail.com"
}

### Login
POST http://localhost:3030/api/login HTTP/1.1
content-type: application/json

{
    "password": "password",
		"username": "admin@gmail.com"
}

### update error
PUT http://localhost:3030/api/users/battlepoap HTTP/1.1
content-type: application/json

{
    "name": "Poap",
		"username": "realpoap"
}

###
GET http://localhost:3030/api/authors HTTP/1.1
content-type: application/json
