POST http://localhost:3030/api/blogs HTTP/1.1
content-type: application/json

{
    "author": "Poap",
    "url": "www.blogexample.com/31",
		"title": "A new blog example",
		"likes": 0
}

###

PUT http://localhost:3030/api/blogs/2 HTTP/1.1
content-type: application/json

{
		"likes": 3
}

###

DELETE http://localhost:3030/api/blogs/2 HTTP/1.1
content-type: application/json

### bad POST request
POST http://localhost:3030/api/blogs HTTP/1.1
content-type: application/json

{
    "author": "Poap",
		"title": "A new blog example",
		"likes": 0
}

### bad PUT request
PUT http://localhost:3030/api/blogs/1 HTTP/1.1
content-type: application/json

{
		"likes": "super"
}

###
GET http://localhost:3030/api/users HTTP/1.1
content-type: application/json

###
POST http://localhost:3030/api/users HTTP/1.1
content-type: application/json

{
    "name": "Poap",
		"username": "withmailpoap@gmail.com"
}

### update error
PUT http://localhost:3030/api/users/battlepoap HTTP/1.1
content-type: application/json

{
    "name": "Poap",
		"username": "realpoap"
}