POST http://localhost:3030/api/blogs HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IndpdGhtYWlscG9hcEBnbWFpbC5jb20iLCJpZCI6NCwiaWF0IjoxNzUyNjI0NjE5fQ.I9ctZqr9vO4oh9ZuNvEDPC1W4MnZvD4x467DEMRJ-CU

{
    "author": "Poap",
    "url": "www.blogexample.com/31",
		"title": "A new blog example",
		"likes": 0
}

###

PUT http://localhost:3030/api/blogs/2 HTTP/1.1
content-type: application/json

{
		"likes": 3
}

###

DELETE http://localhost:3030/api/blogs/3 HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IndpdGhtYWlscG9hcEBnbWFpbC5jb20iLCJpZCI6NCwiaWF0IjoxNzUyNjI0NjE5fQ.I9ctZqr9vO4oh9ZuNvEDPC1W4MnZvD4x467DEMRJ-CU

### bad POST request
POST http://localhost:3030/api/blogs HTTP/1.1
content-type: application/json

{
    "author": "Poap",
		"title": "A new blog example",
		"likes": 0
}

### bad PUT request
PUT http://localhost:3030/api/blogs/1 HTTP/1.1
content-type: application/json

{
		"likes": "super"
}

###
GET http://localhost:3030/api/users HTTP/1.1
content-type: application/json

###
POST http://localhost:3030/api/users HTTP/1.1
content-type: application/json

{
    "name": "Poap",
		"username": "withmailpoap@gmail.com"
}

### Login
POST http://localhost:3030/api/login HTTP/1.1
content-type: application/json

{
    "password": "password",
		"username": "withmailpoap@gmail.com"
}

### update error
PUT http://localhost:3030/api/users/battlepoap HTTP/1.1
content-type: application/json

{
    "name": "Poap",
		"username": "realpoap"
}